####################################################################################################
# Border
####################################################################################################
default_border pixel 1
default_floating_border pixel 1
for_window [class=firefox] border toggle 1

####################################################################################################
# Colors
####################################################################################################
set_from_resource $darkred     color1  #000000
set_from_resource $red         color9  #000000
set_from_resource $darkgreen   color2  #000000
set_from_resource $green       color10 #000000
set_from_resource $darkyellow  color3  #000000
set_from_resource $yellow      color11 #000000
set_from_resource $darkblue    color4  #000000
set_from_resource $blue        color12 #000000
set_from_resource $darkmagenta color5  #000000
set_from_resource $magenta     color13 #000000
set_from_resource $darkcyan    color6  #000000
set_from_resource $cyan        color14 #000000
set_from_resource $darkwhite   color7  #000000
set_from_resource $white       color15 #000000

# Use custom colors for black
set $black       #282828
set $darkblack   #1d2021
set $transparent #00000000

# class                 border  backgr. text    indicator child_border
client.focused          #d65d0e #d65d0e #fbf1c7 #d65d0e   #d65d0e
client.focused_inactive #282828 #282828 #fbf1c7 #282828   #282828
client.unfocused        #282828 #282828 #fbf1c7 #282828   #282828
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
client.background       #ffffff
