# set refresh rate for each monitor to highest possible
exec_always --no-startup-id $config/i3/scripts/set-highest-rate.sh
# set brightness, red light etc
exec_always --no-startup-id $config/i3/scripts/monitors.sh

#exec_always xrandr --output eDP1 --mode 1920x1080 --pos 0x1080 --rotate normal --output HDMI2 --primary --mode 3840x2160 --pos 1920x0 --rotate normal

