# Mullvad
bindsym $mod+$caps+Shift+a exec --no-startup-id "if mullvad lockdown-mode get | grep ': on'; then mullvad lockdown-mode set off && msg='Lockdown mode OFF' ; else mullvad lockdown-mode set on && msg='Lockdown mode ON' ; fi ; notify-send \\"$msg\\" -t 4500 ; unset msg"
